import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { parseTextbook } from "../lib/content/parseTextbook";
import { parsePracticeAnswers } from "../lib/content/parsePracticeTable";
import type { PracticeAnswer, PracticeQuestion } from "../lib/content/types";

const MD = "GIAI ĐOẠN 1-2-3 - Giáo trình hoàn chỉnh.md";
const OUT = "content/textbook.ts";

const md = readFileSync(join(process.cwd(), MD), "utf8");
const book = parseTextbook(md);

// Merge Ch12 answers into practice questions
const lastAnswerIdx = md.lastIndexOf("ĐÁP ÁN VÀ GIẢI THÍCH");
const answers: PracticeAnswer[] = lastAnswerIdx >= 0
  ? parsePracticeAnswers(md.slice(lastAnswerIdx))
  : [];
const answerByOrdinal = new Map(answers.map((a) => [a.ordinal, a]));

// Parse Ch12 prompts from markdown
const ch12Slug = "bai-tap-chuyen-sau-100-cau-word-form-toeic";
const ch12 = book.allChapters.find((c) => c.slug === ch12Slug);
if (ch12) {
  // Extract prompts from the raw markdown for this chapter
  const ch12Start = md.indexOf("## CHƯƠNG 12:");
  const ch12End = md.indexOf("## CHƯƠNG 13:", ch12Start);
  const ch12Md = md.slice(ch12Start, ch12End > 0 ? ch12End : undefined);
  const promptMatches = [...ch12Md.matchAll(/\*\*Câu (\d+):\*\*\s*(.+?)\s*\(([^\)]+)\)/g)];
  const questions: PracticeQuestion[] = promptMatches.map((m) => {
    const ordinal = Number(m[1]);
    const prompt = m[2].trim();
    const baseWord = m[3].trim();
    const a = answerByOrdinal.get(ordinal);
    return {
      id: `${ch12Slug}-q${ordinal}`,
      chapterSlug: ch12Slug,
      ordinal,
      prompt,
      kind: "fill_in_blank" as const,
      answer: a?.answer ?? "",
      answerWord: baseWord,
      partOfSpeech: a?.partOfSpeech ?? "Khác",
      explanation: a?.explanation ?? "",
    };
  });
  ch12.practiceQuestions = questions;
}

mkdirSync(join(process.cwd(), "content"), { recursive: true });

const banner = "// AUTO-GENERATED by scripts/build-content.ts. DO NOT EDIT.\n// Source: GIAI ĐOẠN 1-2-3 - Giáo trình hoàn chỉnh.md\n\n";
const body = `import type { Textbook } from "../lib/content/types";\n\nexport const textbook: Textbook = ${JSON.stringify(book, null, 2)};\n\nexport default textbook;\n`;
writeFileSync(join(process.cwd(), OUT), banner + body);
console.log(`Wrote ${OUT} (${book.stages.length} stages, ${book.allChapters.length} chapters).`);
console.log(`  Ch12 has ${ch12?.practiceQuestions?.length ?? 0} practice questions.`);
